version: '3.8'

services:
    app:
        build: .
        container_name: todo-app
        ports:
            - "8001:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite

    test:
        build: .
        container_name: todo-app-test
        command: [ "php", "artisan", "test" ]
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=testing
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
